### ISSUE TITLE
no EFIL assumption in code

### ISSUE THREAD

**Issue by Egg-Hu** [IandRover/MAML_noisy_contrasive_learner#1]
A clear code! I have two questions...
1. Where is the implementation of EFIL assumption in the code. It seems the encoder parameters are also updated (fast parameters) in the inner loop in the code.
2. Where is the explicit loss implementation in the code. I only find the final results of this part.

**Comment by IandRover** [comment]
Hi, Egg-Hu.
1. While our analysis heavily relies on the EFIL assumption, the experimental results (especially Sec. 3.3, 3.4, 3.5) compare vanilla MAML with the proposed zeroing trick. We only explicitly implement the EFIL assumption in Fig.8.
2. I will update the code soon : )

**Comment by IandRover** [comment]
I just uploaded the code for the exact reformulation of MAML as a contrastive learning algorithm, which should solve both of your problems. As I am on military duty at the moment, I am not able to answer you immediately. Sorry for the inconvenience.
